//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTyping.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KeyLayout {
            get {
                return ((string)(this["KeyLayout"]));
            }
            set {
                this["KeyLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KeyLayoutDataDir {
            get {
                return ((string)(this["KeyLayoutDataDir"]));
            }
            set {
                this["KeyLayoutDataDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PracticeDataDir {
            get {
                return ((string)(this["PracticeDataDir"]));
            }
            set {
                this["PracticeDataDir"] = value;
            }
        }

        /// <summary>
        /// <260812_12> 자리연습의 타속(타수) 계산 방법. "simple" = 간단 방식(정타 수 ÷ 분),
        /// "original" = 원래 방식(글자수 환산 ÷ 분 × 정확도).
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("simple")]
        public string TpmMethod {
            get {
                return ((string)(this["TpmMethod"]));
            }
            set {
                this["TpmMethod"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FingerLayerEnabled {
            get {
                return ((bool)(this["FingerLayerEnabled"]));
            }
            set {
                this["FingerLayerEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.5")]
        public double FingerLayerThickness {
            get {
                return ((double)(this["FingerLayerThickness"]));
            }
            set {
                this["FingerLayerThickness"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        // <260812_16> 처음 설치한 PC 의 손 모양 윤곽선 색: 견본 7번째(주황).
        [global::System.Configuration.DefaultSettingValueAttribute("#F76707")]
        public string FingerLayerColor {
            get {
                return ((string)(this["FingerLayerColor"]));
            }
            set {
                this["FingerLayerColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.65")]
        public double FingerLayerOpacity {
            get {
                return ((double)(this["FingerLayerOpacity"]));
            }
            set {
                this["FingerLayerOpacity"] = value;
            }
        }
    }
}
