<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>OpenTyping</RootNamespace>
    <AssemblyName>열린타자</AssemblyName>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyTitle>OpenTyping</AssemblyTitle>
    <Product>OpenTyping</Product>
    <Copyright>Copyright © 2018</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.5" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="MahApps.Metro.IconPacks.FontAwesome" Version="6.2.1" />
    <PackageReference Include="MahApps.Metro.IconPacks.Modern" Version="6.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\NanumGothic.ttf" />
    <Resource Include="Resources\Fonts\NanumGothicBold.ttf" />
    <Resource Include="Resources\Fonts\NanumGothicExtraBold.ttf" />
    <Resource Include="Resources\Fonts\NanumBarunGothic.ttf" />
    <Resource Include="Resources\Fonts\NanumBarunGothicBold.ttf" />
    <Resource Include="Resources\Fonts\NanumBarunGothicLight.ttf" />
    <Resource Include="Resources\Fonts\NanumBarunGothicUltraLight.ttf" />
    <Resource Include="Resources\icon.png" />
    <Resource Include="Resources\logo.png" />
    <Resource Include="icon.ico" />
  </ItemGroup>

</Project>
